# test
lhs: 6
rhs: 8
op: "*"


arcgis:
#  prourl: gis2.sy.gov
#  host: gis2.sy.gov
  prourl: gis2.sy.gov
  host: gis2.sy.gov
  outputDwgUrl: https://gis2.sy.gov/arcgis/rest/services/tools/outputCAD/GPServer/outputCAD
  outputDwgDownloadUrl:  http://www.myarcgis.com/download/
  outputallDwgUrl:  https://gis2.sy.gov/arcgis/rest/services/tools/outputPolygon/GPServer/outputCadPolygon
  featureToCadDownloadUrl:  http://www.myarcgis.com/download/
  featureToCadurl: https://gis2.sy.gov/arcgis/rest/services/tools/featureToCad/GPServer/featureToCad
  geometryServerUrl: https://gis2.sy.gov/arcgis/rest/services/Utilities/Geometry/GeometryServer
#  outputDwgUrl: https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/tools/outputCAD/GPServer/outputCAD
#  outputDwgDownloadUrl: https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/directories/arcgisjobs/tools/outputCAD_gpserver/
#  outputallDwgUrl:  https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/tools/outputCadPolygon/GPServer/outputCadPolygon
#  featureToCadDownloadUrl:  https://j1e2z89dc5bgu24.arcgis.cn/arcgis/directories/arcgisjobs/tools/featuretocad_gpserver/
#  featureToCadurl: https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/tools/featureToCad/GPServer/featureToCad
#  geometryServerUrl: https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/Utilities/Geometry/GeometryServer


  featureUrl:
    temppolygonUrl: https://gis2.sy.gov/arcgis/rest/services/SY/tempPolygon/FeatureServer/0
    riverUrl: https://gis2.sy.gov/arcgis/rest/services/SY/shuiyu/MapServer
    riverQzjUrl: https://gis2.sy.gov/arcgis/rest/services/SY/shuiyu2/MapServer
    otherUrl: https://gis2.sy.gov/arcgis/rest/services/SY/qt/MapServer
    bgtxUrl: https://gis2.sy.gov/arcgis/rest/services/SY/BGTX/MapServer
    hxUrl: https://gis2.sy.gov/arcgis/rest/services/SY/HXAA/FeatureServer/0
    hxSearchUrl:  https://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/SY/HXAA/MapServer
#    temppolygonUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/temp/FeatureServer/0
#    riverUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/shuiyu/MapServer
#    riverQzjUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/shuiyu2/MapServer
#    otherUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/other/MapServer
#    bgtxUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/bgtx/MapServer
#    hxUrl: http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/hxaa/FeatureServer/0
#    hxSearchUrl:  http://j1e2z89dc5bgu24.arcgis.cn/arcgis/rest/services/river/hxaa/MapServer
  token:
    username: siteadmin
    password: d/AyzpE4K+tj+oPt+6zRBQ==
    #password: kGGHjSUL0cAUij1rDbNJbg==
    referer: gis2.sy.gov/index

project:
  host: gis2.sy.gov


# config start
server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
  mvc:
    static-path-pattern: /**
  servlet:
    context-path:
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  mapper-locations: classpath:/mybatis/*
  type-aliases-package: com.clb
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:
  upload:
    temporarypath: D:/temp/
    path: D:/uploadFile/

spring:
#  mvc:
#  suffix: .jsp
#  prefix: classpath:/jsp/
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: coretdkcSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/sy
#    url: jdbc:postgresql://j1e2z89dc5bgu24.arcgis.cn:5432/shuiyu
    username: sde
    password: sde123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        # 将format_sql 配置为ture，将会格式化sql语句，
        format_sql: true
        # 这个配置与show-sql: true配置重复，只配置一个即可
        show_sql: true


  thymeleaf:
    enabled: true
    cache: false
    mode: HTML
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
    serialization:
      write-dates-as-timestamps: true
