# test
lhs: 6
rhs: 8
op: "*"

#appkey: e2a6205ec33511e9b83200ff5f8a2c01
#appsecret: 03ecfc8cc33611e9b83200ff
appkey: f6c00a004f764f92a6afd64ab451bb23
appsecret: 7a53ca1ab59147d1

ticketValidateUrl: https://sgpt.zjwater.com/oapi/water-manage-auth/api/ssologin/validateTicket
sptUrl: https://sgpt.zjwater.com



arcgis:
#  prourl: j1e2z89dc5bgu24.arcgis.cn
  outputDwgUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/tools/outputCAD/GPServer/outputCAD
  outputDwgDownloadUrl:  https://gis2.cxzhsl.cn/myarcgis/download/
  outputallDwgUrl:  https://gis2.cxzhsl.cn/arcgis/rest/services/tools/outputPolygon/GPServer/outputCadPolygon
  featureToCadDownloadUrl:  https://gis2.cxzhsl.cn/myarcgis/download/
  featureToCadurl: https://gis2.cxzhsl.cn/arcgis/rest/services/tools/featureToCad/GPServer/featureToCad
  geometryServerUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/Utilities/Geometry/GeometryServer
  accessKey: 27c463b0e5ba4b5e8cefee48cf60dfce
  secretKey: 56a84949937d4f9b8cd3d6a166b2d757
  tdtToken: fac43bd612f98b93bacda49ccb3af69c
  referer: 192.168.200.147

  featureUrl:
    tdtJjUrl: https://bcdsg.zj.gov.cn:8443/restapi/prod/IC33000020220315000001/services/wmts/emap/default/oss
    tdtJjZjUrl: https://bcdsg.zj.gov.cn:8443/restapi/prod/IC33000020220323000008/services/wmts/emap_lab/default/oss
    tdtYxUrl: https://bcdsg.zj.gov.cn:8443/restapi/prod/IC33000020220406000002/services/wmts/imgmap/default/oss
    tdtYxZjUrl: https://bcdsg.zj.gov.cn:8443/restapi/prod/IC33000020220411000002/services/wmts/imgmap_lab/default/oss
    tdtDxUrl: https://bcdsg.zj.gov.cn:8443/restapi/prod/IC33000020220406000007/services/wmts/zjemap_ter/default/oss
    tdtNbDzUrl: https://interface.zjzwfw.gov.cn/gateway/component/routing/agent.htm
    temppolygonUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/tempPolygon/FeatureServer/0
    riverUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/shuiyu/MapServer
    riverQzjUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/shuiyu2/MapServer
    otherUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/qt/MapServer
    bgtxUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/BGTX/MapServer
    hxUrl: https://gis2.cxzhsl.cn/arcgis/rest/services/SY/HXAA/FeatureServer/0
    hxSearchUrl:  https://gis2.cxzhsl.cn/arcgis/rest/services/SY/HXAA/MapServer
  token:
    username: siteadmin
    password: sYBRQGpsgtciMZapyV6G4A==
    #密码:cxzhsl@2022

server:
  port: 8088
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
  mvc:
    static-path-pattern: /**
  servlet:
    context-path:
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  mapper-locations: classpath:/mybatis/*
  type-aliases-package: com.clb
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload:
    temporarypath: D:/temp/
    path: D:/uploadFile/

spring:
#  mvc:
#  suffix: .jsp
#  prefix: classpath:/jsp/
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: coretdkcSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/sy
    username: sde
    password: sde123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        # 将format_sql 配置为ture，将会格式化sql语句，
        format_sql: true
        # 这个配置与show-sql: true配置重复，只配置一个即可
        show_sql: true
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
    serialization:
      write-dates-as-timestamps: true
