server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:5432/vueblog2?useUnicode=true&characterEncoding=utf-8
    username: vueblog
    password: 123123
    driverClassName: org.postgresql.Driver