# test
lhs: 6
rhs: 8
op: "*"


arcgis:
  host: 192.168.5.120
  mapServerName: river
  username: yzb
  password: 123123

project:
  host: 192.168.5.120


# config start
server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
  mvc:
    static-path-pattern: /**
  servlet:
    context-path:
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/



mybatis:
  mapper-locations: classpath:/mybatis/*
  type-aliases-package: com.clb
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:
  upload:
    temporarypath: /temp/
    path: /statisimg/

spring:
  mvc:
  suffix: .jsp
  prefix: classpath:/jsp/
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: coretdkcSystem
  datasource:
    url: jdbc:postgresql://192.168.5.120:5432/river?useUnicode=true&characterEncoding=utf-8
    username: yzb
    password: 123123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        # 将format_sql 配置为ture，将会格式化sql语句，
        format_sql: true
        # 这个配置与show-sql: true配置重复，只配置一个即可
        show_sql: true


  thymeleaf:
    enabled: true
    cache: false
    mode: HTML
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/html/
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
    serialization:
      write-dates-as-timestamps: true
